### ISSUE TITLE
Provide license under which it is provided

### ISSUE THREAD

**Issue by jkrzemin** [freshautomations/stoml#12]
Hi

I'm glad I've found such useful project, but it could use a license under which it can be used.

**Comment by hoijui** [comment]
please do!

**Comment by greg-szabo** [comment]
Oh, I hope the missing license didn't stop anyone from using (or forking) the project! Such a simple fix, such a huge headache.

I've added an Apache license to the repository, I hope that's permissive enough for your use case.

**Comment by hoijui** [comment]
thank youuu!! :-)
